apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.destination.name | default .Values.source.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    copy.bigbang.dev/secret-name: {{ .Values.source.name }}
    copy.bigbang.dev/secret-namespace: {{ .Values.source.namespace }}
{{- with lookup "v1" "Secret" .Values.source.namespace .Values.source.name }}
data:
{{ toYaml .data | indent 2}}

type: {{ .type }}
{{- end }}


